### ISSUE TITLE
READ ME IS EMPTY

### ISSUE THREAD

**Issue by sree7158** [cryptotronix/yacl#1]
Please share the procedure or steps to  use the library.

**Comment by jbdatko** [comment]
Hey, sorry about that. I made a new branch and update the readme with the basic steps here: https://github.com/cryptotronix/yacl/blob/dev/README.md

If there's any step you are stuck on, feel free to update this issue!

**Comment by bsodmike** [comment]
Seems the branch has shifted to https://github.com/cryptotronix/yacl/tree/develop.
Feel free to close this issue.  

Great stuff @jbdatko, I just emailed you about some thoughts I had on the ATECC508A chip too.

**Comment by jbdatko** [comment]
Finally did a merge to master.
